version: '3.9'

services:
  db:
    image: postgres:13.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5500:5432
    environment:
      - POSTGRES_USER=sakura
      - POSTGRES_PASSWORD=sakura
      - POSTGRES_DB=sakura_dev

  sakura:
    build: ./services/web
    command: flask run --host=0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data: