"""empty message

Revision ID: 1551913491aa
Revises: ccdab66b23aa
Create Date: 2021-06-06 08:54:07.894295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1551913491aa'
down_revision = 'ccdab66b23aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
