"""empty message

Revision ID: 1f968eba63bb
Revises: b563846b2070
Create Date: 2021-06-17 23:04:24.167544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f968eba63bb'
down_revision = 'b563846b2070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_to_appointment', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_to_appointment', 'price')
    # ### end Alembic commands ###
