"""empty message

Revision ID: 2630a01ea4cb
Revises: a58e0ec0119d
Create Date: 2021-06-11 06:15:55.709496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2630a01ea4cb'
down_revision = 'a58e0ec0119d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
