"""empty message

Revision ID: 2da6df0b3424
Revises: 0a1846740b03
Create Date: 2021-06-10 13:43:06.501927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da6df0b3424'
down_revision = '0a1846740b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_name_key', 'client', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('client_name_key', 'client', ['name'])
    # ### end Alembic commands ###
