"""empty message

Revision ID: 489226bf8230
Revises: 6465c3dd66da
Create Date: 2021-06-13 13:40:15.906668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489226bf8230'
down_revision = '6465c3dd66da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salon', sa.Column('translit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salon', 'translit')
    # ### end Alembic commands ###
