"""empty message

Revision ID: 52cca9d2281a
Revises: c31347b36ae3
Create Date: 2021-05-30 23:58:36.730947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cca9d2281a'
down_revision = 'c31347b36ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'hairdresser_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointment', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointment', 'hairdresser_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
