"""empty message

Revision ID: 6465c3dd66da
Revises: fdbdaea442e7
Create Date: 2021-06-13 11:25:54.947971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6465c3dd66da'
down_revision = 'fdbdaea442e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shifts_salon_id_fkey', 'shifts', type_='foreignkey')
    op.drop_constraint('shifts_hairdresser_id_fkey', 'shifts', type_='foreignkey')
    op.create_foreign_key(None, 'shifts', 'hairdresser', ['hairdresser_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shifts', 'salon', ['salon_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.create_foreign_key('shifts_hairdresser_id_fkey', 'shifts', 'hairdresser', ['hairdresser_id'], ['id'])
    op.create_foreign_key('shifts_salon_id_fkey', 'shifts', 'salon', ['salon_id'], ['id'])
    # ### end Alembic commands ###
