"""empty message

Revision ID: 67c80323bb4f
Revises: 1f968eba63bb
Create Date: 2021-06-20 22:47:17.395871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c80323bb4f'
down_revision = '1f968eba63bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_to_appointment', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('service_to_appointment', sa.Column('final_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_to_appointment', 'final_price')
    op.drop_column('service_to_appointment', 'discount')
    # ### end Alembic commands ###
