"""empty message

Revision ID: a2a7f81ce56b
Revises: e498382fb3ab
Create Date: 2021-06-12 14:46:21.971514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a7f81ce56b'
down_revision = 'e498382fb3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('accomplished', sa.Boolean(), nullable=True))
    op.drop_column('appointment', 'happened')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('happened', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('appointment', 'accomplished')
    # ### end Alembic commands ###
