"""empty message

Revision ID: a58e0ec0119d
Revises: 7ef1f539bb3b
Create Date: 2021-06-10 23:44:52.479937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58e0ec0119d'
down_revision = '7ef1f539bb3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_to_appointment',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('appointment_id', 'service_id')
    )
    op.drop_constraint('appointment_service_id_fkey', 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'service_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('appointment_service_id_fkey', 'appointment', 'service', ['service_id'], ['id'])
    op.drop_table('service_to_appointment')
    # ### end Alembic commands ###
