"""empty message

Revision ID: b563846b2070
Revises: 489226bf8230
Create Date: 2021-06-14 09:24:47.514597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b563846b2070'
down_revision = '489226bf8230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'salon', ['translit'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salon', type_='unique')
    # ### end Alembic commands ###
