"""empty message

Revision ID: e498382fb3ab
Revises: e970a360211d
Create Date: 2021-06-12 07:38:31.898856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e498382fb3ab'
down_revision = 'e970a360211d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('happened', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'happened')
    # ### end Alembic commands ###
