"""empty message

Revision ID: e6d2ccc3abf9
Revises: e19e693ad866
Create Date: 2021-06-05 06:27:45.589591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d2ccc3abf9'
down_revision = 'e19e693ad866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('specialization',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('hairdresser_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hairdresser_id'], ['hairdresser.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'hairdresser_id')
    )
    op.drop_constraint('appointment_hairdresser_id_fkey', 'appointment', type_='foreignkey')
    op.create_foreign_key(None, 'appointment', 'hairdresser', ['hairdresser_id'], ['id'], ondelete='SET NULL')
    op.add_column('hairdresser', sa.Column('comment', sa.String(length=500), nullable=True))
    op.drop_column('hairdresser', 'specialization')
    op.add_column('service', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'service', 'type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_column('service', 'type_id')
    op.add_column('hairdresser', sa.Column('specialization', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('hairdresser', 'comment')
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.create_foreign_key('appointment_hairdresser_id_fkey', 'appointment', 'hairdresser', ['hairdresser_id'], ['id'])
    op.drop_table('specialization')
    op.drop_table('type')
    # ### end Alembic commands ###
