"""empty message

Revision ID: e970a360211d
Revises: b4ec3d032805
Create Date: 2021-06-12 00:38:01.841681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e970a360211d'
down_revision = 'b4ec3d032805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('comment', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'comment')
    # ### end Alembic commands ###
